### ISSUE TITLE
No encuentra "afip.pem"

### ISSUE THREAD

**Issue by juansecalvinio** [sarriaroman/AFIP-API#19]
Hola, buenas noches!
Estoy probando el proyecto, y luego de generar el certificado, cuando quiero correro en homo me indica lo siguiente:

`➜  afip-api git:(master) ✗ HOMO=true node server.js

(node:62951) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/juansecalvinio/Documents/programacion/antecedentes/afip-api/keys/afip.pem'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at new Tokens (/Users/juansecalvinio/Documents/programacion/antecedentes/afip-api/helpers/wsaa.js:14:23)
    at Object.<anonymous> (/Users/juansecalvinio/Documents/programacion/antecedentes/afip-api/helpers/wsaa.js:180:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/juansecalvinio/Documents/programacion/antecedentes/afip-api/routes/api/endpoints.js:2:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
(node:62951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:62951) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Saben qué puede ser?
O tal vez me falta alguna acción previa?

Saludos!

**Comment by pimgux** [comment]
Hola tenes que generar el certificado y guardarlo en /Users/juansecalvinio/Documents/programacion/antecedentes/afip-api/keys/ Saludos

**Comment by ramirosacruz** [comment]
Se te generó como .csr, reemplazale por .pem y listo :)

**Comment by ramirosacruz** [comment]
Ya los generé, agarre la key y la coloqué en el generador de PEM de la afip para estar seguro 

Y me aparece esto:

`{
    "result": false,
    "err": "Cannot read property 'logincmsreturn' of undefined"
}`

Desde mi entorno de homologación hice lo siguiente:
- Cambié lo de postman al cuit con el que estoy trabajando, este ya se encuentra habilitado (lo hice desde el portal de la afip). 
- Me descargué la última versión de postman y probé con la que pusieron (la versión de extensión de chrome)
- También me fijé si tal vez era un problema de certificados y generé desde como sugiere la afip, y como pusieron en el readme.md
- Arreglé con `npm audit fix` lo vulnerabilidad
- Tengo las dependencias al día  

El cuit probado es 20189036796
