### ISSUE TITLE
Bug npm i

### ISSUE THREAD

**Issue by alejandroquadri** [sarriaroman/AFIP-API#7]
Aparenemente esta rompiendo al intentar npm install. 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/ale/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/Users/ale/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ale/Dev/afip-api/node_modules/ursa
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN afipapi@0.5.0 No repository field.
npm WARN afipapi@0.5.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa@0.9.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

tenes idea por donde puede andar el problema?

**Comment by alejandroquadri** [comment]
Pude resolverlo. Tenia que ver con la version de soap. Instale la ultima version y anduvo bien.

**Comment by federicobaiocco** [comment]
Hola alejandro, como resolviste el error? Me está pasando lo mismo

**Comment by sarriaroman** [comment]
Hola @federicobaiocco probaste cambiando la versión de node-soap a la última versión disponible? revisa con npm outdated porque seguro viene por ahí 😉

**Comment by emiliobasualdo** [comment]
@alejandroquadri por favor cerrá el issue. 
Muchas gracias!

**Comment by sarriaroman** [comment]
Este issue no existe con la version 0.7.0 :)
